steps:
  # Build the Docker image with env vars from substitutions
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'
      - '--build-arg=VITE_GOOGLE_PLACES_API_KEY=${_VITE_GOOGLE_PLACES_API_KEY}'
      - '--build-arg=VITE_EXA_API_KEY=${_VITE_EXA_API_KEY}'
      - '--build-arg=VITE_REVENUEBASE_API_KEY=${_VITE_REVENUEBASE_API_KEY}'
      - '--build-arg=VITE_SERPAPI_KEY=${_VITE_SERPAPI_KEY}'
      - '--build-arg=VITE_GCP_PROJECT_ID=warp-486714'
      - '--build-arg=VITE_GCP_LOCATION=us-central1'
      - '--build-arg=VITE_VAPI_API_KEY=${_VITE_VAPI_API_KEY}'
      - '--build-arg=VITE_VAPI_PUBLIC_KEY=${_VITE_VAPI_PUBLIC_KEY}'
      - '--build-arg=VITE_VAPI_PHONE_NUMBER_ID=${_VITE_VAPI_PHONE_NUMBER_ID}'
      - '--build-arg=VITE_VAPI_PHONE_NUMBER=${_VITE_VAPI_PHONE_NUMBER}'
      - '--build-arg=VITE_VAPI_ASSISTANT_ID=${_VITE_VAPI_ASSISTANT_ID}'
      - '--build-arg=VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}'
      - '--build-arg=VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}'
      - '--build-arg=VITE_SUPABASE_SERVICE_ROLE_KEY=${_VITE_SUPABASE_SERVICE_ROLE_KEY}'
      - '--build-arg=VITE_RESEND_API_KEY=${_VITE_RESEND_API_KEY}'
      - '--build-arg=VITE_APOLLO_API_KEY=${_VITE_APOLLO_API_KEY}'
      - '--build-arg=VITE_APOLLO_API_KEYS=${_VITE_APOLLO_API_KEYS}'
      - '-t'
      - 'gcr.io/warp-486714/novalyte-abm'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/warp-486714/novalyte-abm']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'novalyte-abm'
      - '--image=gcr.io/warp-486714/novalyte-abm'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'

images:
  - 'gcr.io/warp-486714/novalyte-abm'

options:
  logging: CLOUD_LOGGING_ONLY
