# ── Stage 1: Build ──
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG VITE_GEMINI_API_KEY
ARG VITE_GOOGLE_PLACES_API_KEY
ARG VITE_EXA_API_KEY
ARG VITE_REVENUEBASE_API_KEY
ARG VITE_SERPAPI_KEY
ARG VITE_GCP_PROJECT_ID
ARG VITE_GCP_LOCATION
ARG VITE_VAPI_API_KEY
ARG VITE_VAPI_PUBLIC_KEY
ARG VITE_VAPI_PHONE_NUMBER_ID
ARG VITE_VAPI_PHONE_NUMBER
ARG VITE_VAPI_ASSISTANT_ID
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_SERVICE_ROLE_KEY
ARG VITE_RESEND_API_KEY
RUN npm run build

# ── Stage 2: Serve ──
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
